// common 
export const SHOW_RIGHT_DRAWER = "SHOW_RIGHT_DRAWER";
export const CHANGE_GLOBAL_LOADER_VISIBILITY= "CHANGE_GLOBAL_LOADER_VISIBILITY";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// explore
export const GET_WORD_LIST = "GET_WORD_LIST";
export const GET_WORD_LIST_SUCCESS = "GET_WORD_LIST_SUCCESS";
export const GET_WORD_LIST_FAILURE = "GET_WORD_LIST_FAILURE";
export const UPDATE_WORD_STATUS_BY_ID = "UPDATE_WORD_STATUS_BY_ID";
export const UPDATE_WORD_STATUS_BY_ID_SUCCESS = "UPDATE_WORD_STATUS_BY_ID_SUCCESS";
export const UPDATE_WORD_STATUS_BY_ID_FAILURE = "UPDATE_WORD_STATUS_BY_ID_FAILURE";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";

// auth 
export const UPDATE_USER_LOGGEDIN = "UPDATE_USER_LOGGEDIN";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const REFRESH_ACCESS_TOKEN = "REFRESH_ACCESS_TOKEN";
export const REFRESH_ACCESS_TOKEN_SUCCESS = "REFRESH_ACCESS_TOKEN_SUCCESS";
export const REFRESH_ACCESS_TOKEN_FAILURE = "REFRESH_ACCESS_TOKEN_FAILURE";

// quiz 
export const GENERATE_QUIZ = "GENERATE_QUIZ";
export const GENERATE_QUIZ_SUCCESS = "GENERATE_QUIZ_SUCCESS";
export const GENERATE_QUIZ_FAILURE = "GENERATE_QUIZ_FAILURE";
export const GET_QUIZ_QUESTIONS = "GET_QUIZ_QUESTIONS";
export const GET_QUIZ_QUESTIONS_SUCCESS = "GET_QUIZ_QUESTIONS_SUCCESS";
export const GET_QUIZ_QUESTIONS_FAILURE = "GET_QUIZ_QUESTIONS_FAILURE";
export const PATCH_QUIZ_SOLUTION = "PATCH_QUIZ_SOLUTION";
export const PATCH_QUIZ_SOLUTION_SUCCESS = "PATCH_QUIZ_SOLUTION_SUCCESS";
export const PATCH_QUIZ_SOLUTION_FAILURE = "PATCH_QUIZ_SOLUTION_FAILURE";
export const GET_QUIZ_RESULTS = "GET_QUIZ_RESULTS";
export const GET_QUIZ_RESULTS_SUCCESS = "GET_QUIZ_RESULTS_SUCCESS";
export const GET_QUIZ_RESULTS_FAILURE = "GET_QUIZ_RESULTS_FAILURE";
export const END_QUIZ = "END_QUIZ";
export const END_QUIZ_SUCCESS = "END_QUIZ_SUCCESS";
export const END_QUIZ_FAILURE = "END_QUIZ_FAILURE";